import time
k = ("")
print("Totally importing logic (:")
print("Hello, World")
print("Hello World" , "This is my 100th program and I'm still not good at it :(")
print("000000000000")
time.sleep(1)
print("0          0")
time.sleep(1)
print("0  #   #   0")
time.sleep(1)
print("0    #     0")
time.sleep(1)
print("0  #   #   0")
time.sleep(1)
print("0          0")
time.sleep(1)
print("000000000000")
time.sleep(1)
print("Using logic to build ASCII Art. Rendering now.......")
print("_________________________________________________________________________________________________")
print("______  ___                                 ______  ___      ______              ___       ")
time.sleep(2)
print("__  |/  /_____ _____________ _______      ___   |/  /_____ ___  /_____ ___   ____(_)_____ _ ")
time.sleep(2)
print("__  /|_/ /_  __ `/_  __ \  __ `/_  __ \     __  /|_/ /_  __ `/_  /_  __ `/_ | / /_  /_  __ `/ ")
time.sleep(2)
print("_  /  / / / /_/ /_  / / / /_/ /_  / / /     _  /  / / / /_/ /_  / / /_/ /__ |/ /_  / / /_/ /    ")
time.sleep(2)
print("/_/  /_/  \__,_/ /_/ /_/\__,_/ /_/ /_/      /_/  /_/  \__,_/ /_/  \__,_/ _____/ /_/  \__,_/ ")
time.sleep(2)
print("                                                                                                 ")
time.sleep(2)
print("Press any key to exit")
k = input()
if k is "":
    exit
                                                                                                 


